FROM php:8.2-fpm

WORKDIR /var/www/html


RUN apt-get update
RUN apt-get install -y build-essential git curl unzip

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www
COPY --chown=www:www . /var/www/html
USER www

EXPOSE 9000
CMD ["php-fpm"]
